# Generated by Django 4.1.7 on 2023-03-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_title_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='post',
        ),
    ]
